<a href="https://colab.research.google.com/github/DivyaLakshmi003/ML-tutorial/blob/main/Complete_Numpy_Tutorial_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy - Numerical Python

Advantages of NumPy Python
  1. Allows several Mathematical Operations
  2. Faster Operations

In [1]:
import numpy as np

List vs Numpy - Time Taken

In [2]:
from time import process_time

Time taken by a list

In [16]:
pythonList = [i for i in range(1000000)]

startTime = process_time()

pythonList = [i+5 for i in pythonList]

endTime = process_time()

print(endTime - startTime)

0.12547907599999952


In [17]:
npArray = np.array([i for i in range(1000000)])

startTime = process_time()

npArray += 5

endTime = process_time()

print(endTime - startTime)

0.001291233000001668


Numpy Arrays

In [18]:
# list
list1 = [1, 2, 3, 4, 5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [20]:
# numpy array
numpyArr = np.array([1, 2, 3, 4, 5])
print(numpyArr)
type(numpyArr)

[1 2 3 4 5]


numpy.ndarray

In [21]:
# creating a 1 dimensional array in numpy
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [22]:
a.shape

(5,)

In [23]:
# creating a 2 Dimensional array in numpy
b = np.array([(1, 2, 3, 4, 5), (6, 7, 8, 9, 10)])
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [24]:
b.shape

(2, 5)

In [25]:
# creating an numpy array with floating point values
c = np.array([(1, 2, 3, 4, 5), (6, 7, 8, 9, 10)], dtype = float)
print(c)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


Initialization of numpy array or Initial Placeholders in numpy arrays

In [26]:
# creating a numpy array of Zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [27]:
# creating a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [28]:
# creating a numpy array of particular values
z = np.full((5, 4), 5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [30]:
# creating an identity matrix in numpy
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [32]:
# create a numpy array with random values
b = np.random.random((3, 4))
print(b)

[[0.04578276 0.05086948 0.19220923 0.9141631 ]
 [0.24655212 0.16368987 0.00362509 0.45020376]
 [0.11377492 0.92609998 0.47520179 0.50261049]]


In [33]:
# random integer values array within a specific range
c = np.random.randint(10, 100, (3, 5))
print(c)

[[47 78 84 52 24]
 [54 54 42 88 50]
 [83 15 80 81 30]]


In [35]:
# array of evenly spaced values --> specifying the number of values required
d = np.linspace(10, 30, 6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [36]:
# array of evenly space values --> specifying the step value
e = np.arange(10, 30, 5)
print(e)

[10 15 20 25]


In [37]:
# convert a list to a numpy array
list2 = [10, 20, 20, 30, 40, 50]

np_arr = np.asarray(list2)
print(np_arr)
type(np_arr)

[10 20 20 30 40 50]


numpy.ndarray

In [43]:
# convert a tuple to a numpy array
list3 = (10, 20, 20, 30, 40, 50)
print(type(list3))
np_array = np.asarray(list3)
print(np_array)
type(np_array)

<class 'tuple'>
[10 20 20 30 40 50]


numpy.ndarray

Analysing a numpy array

In [44]:
c = np.random.randint(10, 90, (5, 5))
print(c)

[[40 52 28 43 18]
 [49 30 32 82 61]
 [34 85 44 57 30]
 [13 72 41 64 44]
 [45 52 28 67 60]]


In [45]:
# array dimension
print(c.shape)

(5, 5)


In [46]:
# number of dimensions
print(c.ndim)

2


In [47]:
# number of elements in an array
print(c.size)

25


In [48]:
# checking the data type of the values in the array
print(c.dtype)

int64


Mathematical Operations on a np array

In [49]:
list1 = [1, 2, 3, 4, 5]
list2 = [6, 7, 8, 9, 10]

print(list1 + list2) # concatenates or joins two lists

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [50]:
a = np.random.randint(10, 20, (3, 3))
b = np.random.randint(20, 30, (3, 3))

print(a)
print(b)

[[15 18 19]
 [17 10 14]
 [17 12 11]]
[[23 26 27]
 [25 25 27]
 [29 21 27]]


In [52]:
print(a + b)

[[38 44 46]
 [42 35 41]
 [46 33 38]]


In [53]:
print(a - b)

[[ -8  -8  -8]
 [ -8 -15 -13]
 [-12  -9 -16]]


In [54]:
print(a * b)

[[345 468 513]
 [425 250 378]
 [493 252 297]]


In [55]:
print(a / b)

[[0.65217391 0.69230769 0.7037037 ]
 [0.68       0.4        0.51851852]
 [0.5862069  0.57142857 0.40740741]]


In [56]:
a = np.random.randint(10, 20, (3, 3))
b = np.random.randint(20, 30, (3, 3))

print(a)
print(b)

[[14 11 17]
 [16 19 16]
 [18 18 14]]
[[25 22 24]
 [27 28 27]
 [26 29 26]]


In [57]:
print(np.add(a, b))

[[39 33 41]
 [43 47 43]
 [44 47 40]]


In [59]:
print(np.subtract(a, b))

[[-11 -11  -7]
 [-11  -9 -11]
 [ -8 -11 -12]]


In [60]:
print(np.multiply(a, b))

[[350 242 408]
 [432 532 432]
 [468 522 364]]


In [61]:
print(np.divide(a, b))

[[0.56       0.5        0.70833333]
 [0.59259259 0.67857143 0.59259259]
 [0.69230769 0.62068966 0.53846154]]


Array Manipulation

In [64]:
array = np.random.randint(0, 10, (2, 3))
print(array)
print(array.shape)

[[7 6 6]
 [6 0 6]]
(2, 3)


In [63]:
# transpose of array matrix
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[8 4]
 [0 3]
 [5 0]]
(3, 2)


In [65]:
array = np.random.randint(0, 10, (2, 3))
print(array)
print(array.shape)

[[0 1 4]
 [4 1 4]]
(2, 3)


In [66]:
# another method to transpose a matrix
trans2 = array.T
print(trans2)
print(trans2.shape)

[[0 4]
 [1 1]
 [4 4]]
(3, 2)


In [67]:
# reshaping an array
arr = np.random.randint(0, 10, (2, 3))
print(arr)
print(arr.shape)

[[3 0 4]
 [9 7 9]]
(2, 3)


In [68]:
b = arr.reshape(3,2)
print(b)
print(b.shape)

[[3 0]
 [4 9]
 [7 9]]
(3, 2)
